import type { Metadata } from "next";

import { SmartWalletProvider } from "@/lib/smart-wallet/SmartWalletProvider";
import { MeProvider } from "@/providers";
import { Lexend } from "next/font/google";
import "./globals.css";
const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <MeProvider>
          <SmartWalletProvider>{children}</SmartWalletProvider>
        </MeProvider>
      </body>
    </html>
  );
}
